volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: vikat7t7/kittygram_backend/
    env_file: .env
    volumes:
      - static_volume:/static/
      - media:/app/media/
  frontend:
    env_file: .env
    image: vikat7t7/kittygram_frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: vikat7t7/kittygram_gateway/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static
      - media:/app/media
